# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170303_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='brooklyn_img', max_length=200),
        ),
    ]
